### ISSUE TITLE
Add in model documentation to boundaries

### ISSUE THREAD

**Issue by JamesVaughan** [TravelModellingGroup/XTMF2#30]
Currently the only way to add documentation is either attached to a node or a boundary.  It could be beneficial to be able to add comments / documentation visible to the boundary interface in order to describe what nodes are doing without requiring them to be contained within another boundary.

**Comment by JamesVaughan** [comment]
I am thinking that we would name it a "Documentation Block".  Feedback is appreciated.

**Comment by BrendanReilly** [comment]
I might consider calling it a CommentBlock as opposed to a DocumentationBlock.

**Comment by JamesVaughan** [comment]
Issue is resolved with PR #31.
